language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g jasmine-node
branches:
  only:
  - bramble
deploy:
  provider: s3
  access_key_id: AKIAJUGOXM6YIWNJL4JA
  secret_access_key:
    secure: NHgLUUfeDkoHfjBNTbI2O7i3mKqUP7iXeM0os6ck/MJT0Ki0PSq9tZFP/8622AUbGGMW8saicq9IaDuOS51VmH9k4Fn7VpLgaVQSK1WfjoTevNFr5xrXOuMMFrrwatvpLN5NByyCZ4fwvoYPd6bM9NHLh5jijWjeeeOEfqXXb7Y=
  bucket: cdot-bramble
  local-dir: dist
  upload-dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    repo: humphd/brackets
    branch: bramble

